os:
  - linux

language: node_js

node_js:
  - stable


before_install:
  - npm install -g npm@latest

script:
  - npm run-script test-travis
  #- npm run-script test-sauce

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
