os:
  - linux

language: node_js

node_js:
  - lts/*
  - stable

script:
  - npm run lint
  - npm run test-travis
  - npm run test-sauce

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
